# Generated by Django 3.0.3 on 2020-11-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=4)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PEN', 'PENDIENTE'), ('TER', 'TERMINADO'), ('CUR', 'CURSO')], max_length=3)),
                ('sprint', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=50)),
            ],
        ),
    ]
