# Generated by Django 2.2.3 on 2020-08-31 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='tarea',
        ),
    ]
