# Generated by Django 3.0.3 on 2020-11-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0003_auto_20201120_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='choices',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
