# Generated by Django 3.0.3 on 2020-11-20 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Med', 'Media'), ('Baja', 'Baja')], max_length=10)),
                ('estado', models.CharField(choices=[('PEN', 'PENDIENTE'), ('FIN', 'FINALIZADO'), ('INI', 'INICIADO')], max_length=3)),
                ('descripcion', models.CharField(max_length=50)),
                ('observacion', models.CharField(blank=True, max_length=50, null=True)),
                ('id_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
                ('id_tarea_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarea.Tarea')),
            ],
        ),
    ]
