# Generated by Django 2.2.3 on 2020-08-31 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_remove_proyecto_tarea'),
        ('tarea', '0003_auto_20200821_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='id_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto'),
        ),
    ]
