# Generated by Django 2.2.3 on 2020-08-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0004_tarea_id_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('id_tarea', models.ManyToManyField(blank=True, null=True, to='tarea.Tarea')),
            ],
        ),
    ]
