# Generated by Django 3.0.3 on 2020-09-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('id_tarea', models.ManyToManyField(blank=True, null=True, to='tarea.Tarea')),
            ],
        ),
    ]
