# Generated by Django 3.0.3 on 2020-11-21 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        ('linea_base', '0002_auto_20201120_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineabase',
            name='id_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto'),
        ),
    ]
